

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "bun install && bun run dev"
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data:
